#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink the Mackup config
ln -s $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg

# Fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
cd ~/.oh-my-zsh/themes/
git checkout d6a36b1 agnoster.zsh-theme

# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh

echo 'Install composer'
echo '----------------'
cd ~/.dotfiles

EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
then
    echo 'ERROR: Invalid Composer installer signature'
    rm composer-setup.php
else
    php composer-setup.php --quiet
    rm composer-setup.php
    echo 'move composer to /usr/local/bin/composer'
    sudo mv -f composer.phar /usr/local/bin/composer
fi

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'Install mas'
echo '------------'
brew install mas

echo 'Install node'
echo '-----------'
brew install node

echo 'Install fnm'
echo '-----------'
brew install Schniz/tap/fnm

echo 'Install bat'
echo '-----------'
brew install bat

echo 'Install tldr'
echo '------------'
brew install tldr

echo 'Install pkg-config'
echo '------------------'
brew install pkg-config

echo 'Install prettyping'
echo '------------------'
brew install prettyping

echo 'Install wget'
echo '------------'
brew install wget --overwrite

echo 'Install httpie'
echo '--------------'
brew install httpie

echo 'Install ncdu'
echo '------------'
brew install ncdu

echo 'Install hub'
echo '-----------'
brew install hub

echo 'Install ack'
echo '-----------'
brew install ack

echo 'Install doctl'
echo '-------------'
brew install doctl

echo 'Install brew-cask'
echo '-----------------'
brew tap caskroom/cask
brew install brew-cask

echo 'Allow brew to lookup versions'
echo '-----------------'
brew tap caskroom/versions

echo 'Install some nice quicklook plugins'
echo '-----------------------------------'
brew cask install --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql webp-quicklook suspicious-package

echo 'Install php'
echo '-----------'
brew install php@7.1
brew install php@7.2
brew install php@7.3

echo 'Install imagemagick'
echo '-------------------'
brew install imagemagick

echo 'Install imagick'
echo '---------------'
pecl install imagick

echo 'Install memcached'
echo '-----------------'
pecl install memcached

echo 'Install xdebug'
echo '--------------'
pecl install xdebug

echo 'Install redis'
echo '-------------'
pecl install redis

echo 'Install laravel envoy'
echo '---------------------'
composer global require "laravel/envoy=~1.0"

echo 'Install php-cs-fixer'
echo '--------------------'
composer global require friendsofphp/php-cs-fixer

echo 'Install phpunit-watcher'
echo '---------------------'
composer global require spatie/phpunit-watcher

echo 'Install mixed-content-scanner-cli'
echo '---------------------------------'
composer global require spatie/mixed-content-scanner-cli

echo 'Install laravel valet'
echo '---------------------'
composer global require laravel/valet
valet install

echo 'Install laravel'
echo '---------------------'
composer global require laravel/installer

echo 'Install mysql'
echo '-------------'
brew install mysql@5.7
brew services start mysql@5.7

echo 'Install yarn'
echo '------------'
brew install yarn

echo 'Install ghostscript'
echo '-------------------'
brew install ghostscript

echo 'Install mackup'
echo '--------------'
brew install mackup

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

echo 'Install muse'
echo '---------------------------'
brew cask install muse

echo 'Install eqmac2'
echo '---------------------------'
brew cask install eqmac

echo 'Install tunnelblick'
echo '---------------------------'
brew cask install tunnelblick

echo 'Install mailspring'
echo '---------------------------'
brew cask install mailspring

echo 'Install spectacle'
echo '---------------------------'
brew cask install spectacle

echo 'Install karabiner-elements'
echo '---------------------------'
brew cask install karabiner-elements

echo 'Install spotify'
echo '---------------------------'
brew cask install spotify

echo 'Install beardedspice'
echo '---------------------------'
brew cask install beardedspice

echo 'Install slack'
echo '---------------------------'
brew cask install slack

echo 'Install discord'
echo '---------------------------'
brew cask install discord

echo 'Install iterm2'
echo '---------------------------'
brew cask install iterm2

echo 'Install filezilla'
echo '---------------------------'
brew cask install filezilla

echo 'Install sequel-pro'
echo '---------------------------'
brew cask install sequel-pro

echo 'Install postman'
echo '---------------------------'
brew cask install postman

echo 'Install sketch'
echo '---------------------------'
brew cask install sketch

echo 'Install google-chrome'
echo '---------------------------'
brew cask install google-chrome

echo 'Install firefox'
echo '---------------------------'
brew cask install firefox

echo 'Install tor-browser'
echo '---------------------------'
brew cask install tor-browser

echo 'Install transmission'
echo '---------------------------'
brew cask install transmission

echo 'Install vlc'
echo '---------------------------'
brew cask install vlc

echo 'Install etcher'
echo '---------------------------'
brew cask install etcher

echo 'Install appcleaner'
echo '---------------------------'
brew cask install appcleaner

echo 'Install gnupg'
echo '---------------------------'
brew install gnupg

echo 'Install gpg-suite'
echo '---------------------------'
brew cask install gpg-suite

echo 'Install steam'
echo '---------------------------'
brew cask install steam

echo 'Install libreoffice'
echo '---------------------------'
brew cask install libreoffice

echo 'Install htop'
echo '---------------------------'
brew install htop

echo 'Install git-flow-avh'
echo '---------------------------'
brew install git-flow-avh

echo 'Install sublime-text'
echo '---------------------------'
brew cask install sublime-text
ln -s  "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

# echo 'Install android-studio'
# echo '---------------------------'
# brew cask install android-studio

echo 'Install android-platform-tools'
echo '---------------------------'
brew cask install android-platform-tools

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
# echo '2. Install patched solarized theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Make sure icloud is running first. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your icloud. If you already had a backup via mackup run `mackup restore` You will find more info on Mackup here: https://github.com/lra/mackup.'
echo '2. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '3. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
